[project]
name = "audio-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edge-tts>=7.2.8",
    "pygame>=2.6.1",
    "pyobjc>=12.2.1",
    "pyttsx3>=2.99",
]
[project.scripts]
audio-reader = "audio_reader.main:main"
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
